#!/bin/bash
INST_DIR=.
if [ -L $0 ] ; then
SCRIPT=`ls -l $0 | awk '{print $11}'`
INST_DIR=`dirname $SCRIPT`
fi

PLAYER=vlc
if [ "$2" = "vlc" ] ; then
PLAYER=vlc
elif [ "$2" = "mplayer" ] ; then
PLAYER=mplayer
elif [ "$2" = "mpv" ]; then
PLAYER=mpv
fi
gnome-terminal --disable-factory --geometry=120x3 --hide-menubar -x python $INST_DIR/btclient.py -d ~/Downloads/torrents --debug-log /tmp/btclient.log -p $PLAYER -s eng --bt-download-limit 1000 --bt-upload-limit 400  --choose-subtitles --choose-file "$1" 