#!/bin/bash
INST_DIR=.
if [ -L $0 ] ; then
SCRIPT=`ls -l $0 | awk '{print $11}'`
INST_DIR=`dirname $SCRIPT`
fi

PLAYER=mplayer
if [ "$2" = "vlc" ] ; then
PLAYER=vlc
fi

gnome-terminal --disable-factory --geometry=120x3 --hide-menubar -t "BT Streamer" -x python $INST_DIR/btclient.py -d ~/Downloads/torrents  -p $PLAYER -s eng --bt-download-limit 600 --bt-upload-limit 300 "$1" 